//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOIresult
    {
        public int IDresult { get; set; }
        public Nullable<int> InspectionID { get; set; }
        public string Machine { get; set; }
        public Nullable<short> PanelID { get; set; }
        public string PCBnumber { get; set; }
        public Nullable<System.DateTime> inspectionDate { get; set; }
        public Nullable<System.DateTime> VisualDate { get; set; }
        public string BoardName { get; set; }
        public string ProgramName { get; set; }
        public string User_INSPect { get; set; }
        public string InspectResult { get; set; }
        public string UserInspectionResult { get; set; }
        public string CIRNAME { get; set; }
        public Nullable<System.DateTime> InsertionTime { get; set; }
    }
}
