//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class LazerBase
    {
        public int ID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string ProductName { get; set; }
        public string BoardID { get; set; }
        public string Content { get; set; }
        public bool Marked { get; set; }
        public string Result { get; set; }
        public int IDLaser { get; set; }
        public System.DateTime InsertionDateTime { get; set; }
        public Nullable<short> PCID { get; set; }
    }
}
