//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap_Data
    {
        public int ID { get; set; }
        public int IdLazer { get; set; }
        public string PathPhoto { get; set; }
        public System.DateTime Date { get; set; }
        public int IdDescription { get; set; }
        public int UserID { get; set; }
    }
}
