//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QAEntities : DbContext
    {
        public QAEntities()
            : base("name=QAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Scrap_Description> Scrap_Description { get; set; }
        public virtual DbSet<Scrap_Data> Scrap_Data { get; set; }
        public virtual DbSet<Scrap_Log> Scrap_Log { get; set; }
        public virtual DbSet<Scrap_LogPhoto> Scrap_LogPhoto { get; set; }
        public virtual DbSet<Wave_Users> Wave_Users { get; set; }
        public virtual DbSet<Scrap_Code> Scrap_Code { get; set; }
        public virtual DbSet<Scrap_StatusList> Scrap_StatusList { get; set; }
        public virtual DbSet<Scrap_Status> Scrap_Status { get; set; }
        public virtual DbSet<Scrap_Culprit> Scrap_Culprit { get; set; }
        public virtual DbSet<Scrap_DefectCode> Scrap_DefectCode { get; set; }
    }
}
