//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap_Log
    {
        public int id { get; set; }
        public int IdLazer { get; set; }
        public bool Status { get; set; }
        public string PathDocument { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> IdPathPhoto { get; set; }
        public string Code { get; set; }
        public string DefectCode { get; set; }
    }
}
