//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap_Culprit
    {
        public int id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}
