//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMDCOMPONETSEntities1 : DbContext
    {
        public SMDCOMPONETSEntities1()
            : base("name=SMDCOMPONETSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AOIresult> AOIresult { get; set; }
        public virtual DbSet<LazerBase> LazerBase { get; set; }
        public virtual DbSet<THTStart> THTStart { get; set; }
    }
}
