//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrap
{
    using System;
    using System.Collections.Generic;
    
    public partial class THTStart
    {
        public string PCBserial { get; set; }
        public bool AOIpass { get; set; }
        public bool AOIverify { get; set; }
        public System.DateTime PCBScanTime { get; set; }
        public Nullable<short> PCID { get; set; }
        public Nullable<bool> LaserStatus { get; set; }
        public bool PCBResult { get; set; }
        public int IDstartTHT { get; set; }
    }
}
